# Generated by Django 3.1.3 on 2020-11-05 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='similar_file',
            new_name='identical_file',
        ),
        migrations.AlterField(
            model_name='file',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add time'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='file',
            name='descriptions',
            field=models.TextField(blank=True, default=None, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_clone',
            field=models.BooleanField(default=False, verbose_name='Clone of another file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='filesystem.hash', verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='_', max_length=64, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='files', to='tags.Tag', verbose_name='Tags'),
        ),
    ]
