# Generated by Django 3.1.3 on 2020-11-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_auto_20201105_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-add_time']},
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_clone',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.FilePathField(blank=True, default=None, null=True, path='/home/usr/media/files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='identical_file',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='filesystem.file', verbose_name='Previously created identical file'),
        ),
    ]
