# Generated by Django 3.1.3 on 2020-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='_', max_length=64, unique=True, verbose_name='Tag slug'),
        ),
    ]
